devops/devops/urls.py
from django.contrib import admin
from django.urls import path,re_path,include
from dashboard import views


urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('^$',views.index, name="index"),          # 登陆后台首页接口
    re_path('^login/$',views.login, name="login"),    # login登陆接口
    re_path('^logout/$',views.logout, name="logout"),    # logout退出登录接口
    re_path('^namespace_api/$',views.namespace_api, name="namespace_api"),    # 匿名空间api接口
    re_path('^node_resource/$', views.node_resource, name="node_resource"),   # index页面调用的计算资源接口
    re_path('^export_resource_api/$',views.export_resource_api, name="export_resource_api"),    # 编写yaml获取数据接口
    re_path('^ace_editor/$',views.ace_editor, name="ace_editor"),    # 编写yaml获取数据接口
    path('k8s/', include(('k8s.urls', 'k8s'), namespace='k8s')),            # k8s模块
    path('workload/', include(('workload.urls', 'workload'), namespace='workload')),     # workload模块
    path('loadbalancer/', include(('loadbalancer.urls', 'loadbalancer'), namespace='loadbalancer')),    # loadbalancer模块
    path('storage/', include(('storage.urls', 'storage'), namespace='storage')),    # storage模块，主要用于存储一些文件配置与存储

]

devops/k8s/urls.py
from django.urls import path,re_path
from k8s import views


urlpatterns = [
    re_path('^nodes/$',views.nodes, name="nodes"),                # node调用的前端页面调用接口
    re_path('^namespaces/$',views.namespaces, name="namespaces"),        # namespaces调用的前端页面展示接口
    re_path('^PersistentVolumes/$',views.PersistentVolumes, name="PersistentVolumes"),        # pv前端展示接口
    re_path('^node_api/$',views.node_api, name="node_api"),                       # 调用的node_api接口
    re_path('^node_details/$',views.node_details, name="node_details"),           # 调用node详情页前端页面展示接口
    re_path('^node_details_pod_list/$',views.node_details_pod_list, name="node_details_pod_list"),    # 调用node详情页，后端api接口
    re_path('^pv_api/$',views.pv_api, name="pv_api"),            # pv调用的后端的api接口
    re_path('^pv_create/$',views.pv_create, name="pv_create"),     # 创建pv调用的前端接口

]

devops/k8s/models.py
from django.db import models

# Create your models here.

devops/k8s/views.py
from django.shortcuts import render
from django.http import JsonResponse, QueryDict,HttpResponse
from kubernetes import client, config
from devops import k8s_tools  # 导入k8s登陆封装
from dashboard import node_data   # 导入详情计算模块

# Create your views here.
@k8s_tools.self_login_required
def nodes(request):
    return render(request, "k8s/nodes.html")
@k8s_tools.self_login_required
def node_details(request):
    auth_type = request.session.get("auth_type")
    token = request.session.get("token")
    k8s_tools.load_auth_config(auth_type, token)
    core_api = client.CoreV1Api()

    node_name = request.GET.get("node_name", None)
    n_r = node_data.node_resource(core_api, node_name)
    n_i = node_data.node_info(core_api, node_name)

    return render(request, 'k8s/node_details.html', {"node_name": node_name,"node_resouces": n_r, "node_info": n_i})


@k8s_tools.self_login_required
def node_details_pod_list(request):
    auth_type = request.session.get("auth_type")
    token = request.session.get("token")
    k8s_tools.load_auth_config(auth_type, token)
    core_api = client.CoreV1Api()

    node_name = request.GET.get("node_name", None)

    data = []
    try:
        for pod in core_api.list_pod_for_all_namespaces().items:
            name = pod.spec.node_name
            pod_name = pod.metadata.name
            namespace = pod.metadata.namespace
            status = ("运行中" if pod.status.conditions[-1].status else "异常")
            host_network = pod.spec.host_network
            pod_ip = ( "主机网络" if host_network else pod.status.pod_ip)
            create_time = k8s_tools.dt_format(pod.metadata.creation_timestamp)

            if name == node_name:
                if len(pod.spec.containers) == 1:
                    cpu_requests = "0"
                    cpu_limits = "0"
                    memory_requests = "0"
                    memory_limits = "0"
                    for c in pod.spec.containers:
                        # c_name = c.name
                        # c_image= c.image
                        cpu_requests = "0"
                        cpu_limits = "0"
                        memory_requests = "0"
                        memory_limits = "0"
                        if c.resources.requests is not None:
                            if "cpu" in c.resources.requests:
                                cpu_requests = c.resources.requests["cpu"]
                            if "memory" in c.resources.requests:
                                memory_requests = c.resources.requests["memory"]
                        if c.resources.limits is not None:
                            if "cpu" in c.resources.limits:
                                cpu_limits = c.resources.limits["cpu"]
                            if "memory" in c.resources.limits:
                                memory_limits = c.resources.limits["memory"]
                else:
                    c_r = "0"
                    c_l = "0"
                    m_r = "0"
                    m_l = "0"
                    cpu_requests = ""
                    cpu_limits = ""
                    memory_requests = ""
                    memory_limits = ""
                    for c in pod.spec.containers:
                        c_name = c.name
                        # c_image= c.image
                        if c.resources.requests is not None:
                            if "cpu" in c.resources.requests:
                                c_r = c.resources.requests["cpu"]
                            if "memory" in c.resources.requests:
                                m_r = c.resources.requests["memory"]
                        if c.resources.limits is not None:
                            if "cpu" in c.resources.limits:
                                c_l = c.resources.limits["cpu"]
                            if "memory" in c.resources.limits:
                                m_l = c.resources.limits["memory"]

                        cpu_requests += "%s=%s<br>" % (c_name, c_r)
                        cpu_limits += "%s=%s<br>" % (c_name, c_l)
                        memory_requests += "%s=%s<br>" % (c_name, m_r)
                        memory_limits += "%s=%s<br>" % (c_name, m_l)

                pod = {"pod_name": pod_name, "namespace": namespace, "status": status, "pod_ip": pod_ip,
                    "cpu_requests": cpu_requests, "cpu_limits": cpu_limits, "memory_requests": memory_requests,
                    "memory_limits": memory_limits,"create_time": create_time}
                data.append(pod)

        page = int(request.GET.get('page',1))
        limit = int(request.GET.get('limit'))
        start = (page - 1) * limit
        end = page * limit
        data = data[start:end]
        count = len(data)
        code = 0
        msg = "获取数据成功"
        res = {"code": code, "msg": msg, "count": count, "data": data}
        return JsonResponse(res)
    except Exception as e:
        print(e)
        status = getattr(e, "status")
        if status == 403:
            msg = "没有访问权限！"
        else:
            msg = "查询失败！"
        res = {"code": 1, "msg": msg}
        return JsonResponse(res)

@k8s_tools.self_login_required
def namespaces(request):
    return render(request, "k8s/namespaces.html")

@k8s_tools.self_login_required
def PersistentVolumes(request):
    return render(request, "k8s/PersistentVolumes.html")

# 创建pv页面
@k8s_tools.self_login_required
def pv_create(request):
    return render(request,"k8s/pv_create.html")


# node_api接口
@k8s_tools.self_login_required
def node_api(request):
    # 命名空间接口
    code = 0
    msg = "执行数据返回成功"
    # 获取认证的信息
    auth_type = request.session.get("auth_type")
    token = request.session.get("token")
    k8s_tools.load_auth_config(auth_type, token)
    core_api = client.CoreV1Api()
    # 命名空间选择和命名空间表格同时使用
    if request.method == "GET":


        # 获取搜索分页的传回来的值
        search_key = request.GET.get("search_key")

        # 空列表
        data = []
        try:
            # 查找node显示数据
            for i in core_api.list_node_with_http_info()[0].items:
                name = i.metadata.name
                labels = i.metadata.labels
                status = i.status.conditions[-1].status
                scheduler = ("是" if i.spec.unschedulable is None else "否")
                cpu = i.status.capacity['cpu']
                memory = i.status.capacity['memory']
                kebelet_version = i.status.node_info.kubelet_version
                cri_version = i.status.node_info.container_runtime_version
                create_time = k8s_tools.dt_format(i.metadata.creation_timestamp)    # 优化时间返回格式

                node = {"name": name, "labels": labels, "status": status,
                        "scheduler": scheduler, "cpu": cpu, "memory": memory,
                        "kebelet_version": kebelet_version, "cri_version": cri_version,
                        "create_time": create_time}

                # 根据前端返回的搜索key进行判断，查询关键字返回数据
                search_key = request.GET.get('searchkey', None)
                if search_key:
                    if search_key == name:
                        data.append(node)
                    elif search_key in name:
                        data.append(node)
                else:
                    data.append(node)

                code = 0
                msg = "执行数据返回成功"
        except Exception as e:
            code = 1
            # 获取返回状态吗，进行数据判断
            status = getattr(e, "status")
            if status == 403:
                msg = "没有访问权限"
            else:
                msg = "获取数据失败"

        # 统计有多少行数据
        count = len(data)


        # 分页
        page = int(request.GET.get('page', 1))
        limit = int(request.GET.get('limit'))
        # 从哪里开始切
        start = (page - 1) * limit
        # 结束
        end = page * limit

        # 重新封装数据
        data = data[start:end]

        res = {"code": code, "msg": msg, "count": count, "data": data}
        return JsonResponse(res)
    elif request.method == "DELETE":
        # 通过QueryDict 获取ajax提交提交的删除data返回参数
        request_data = QueryDict(request.body)

        # 通过变量获取name参数
        name = request_data.get("name")

        try:
            core_api.delete_node(name)  # 删除node节点
            code = 0
            msg = "删除成功"
        except Exception as e:
            code = 1
            # 获取返回状态吗，进行数据判断
            status = getattr(e, "status")
            if status == 403:
                msg = "没有删除权限"
            else:
                msg = "删除失败"
        res = {"code": code, "msg": msg}
        return JsonResponse(res)


# pv_api接口
@k8s_tools.self_login_required
def pv_api(request):
    # 命名空间接口
    code = 0
    msg = "执行数据返回成功"
    # 获取认证的信息
    auth_type = request.session.get("auth_type")
    token = request.session.get("token")
    k8s_tools.load_auth_config(auth_type, token)
    core_api = client.CoreV1Api()
    # 命名空间选择和命名空间表格同时使用
    if request.method == "GET":


        # 获取搜索分页的传回来的值
        search_key = request.GET.get("search_key")

        # 数据空列表
        data = []
        try:
            # 查找node显示数据
            for pv in core_api.list_persistent_volume().items:
                # print(pv)
                # nfs = pv.spec.nfs.server     # 提前字段
                # print(nfs)
                name = pv.metadata.name
                capacity = pv.spec.capacity["storage"]
                access_modes = pv.spec.access_modes
                reclaim_policy = pv.spec.persistent_volume_reclaim_policy
                status = pv.status.phase
                if pv.spec.claim_ref is not None:
                    pvc_ns = pv.spec.claim_ref.namespace
                    pvc_name = pv.spec.claim_ref.name
                    pvc = "%s / %s" % (pvc_ns, pvc_name)
                else:
                    pvc = "未绑定"
                storage_class = pv.spec.storage_class_name
                create_time = k8s_tools.dt_format(pv.metadata.creation_timestamp)      # 优化时间返回格式

devops/templates/k8s/PersistentVolumes.html
{% extends "base.html" %}

<!--头部-->
{% block title %} pv节点 {% endblock %}
<!-停留的样式-->
<!--layui-nav-itemed 为开关-->
{% block nav-item-1 %} layui-nav-itemed {% endblock %}

<!--layui-this 停留的背景颜色-->
{% block nav-this-1-3 %} layui-this {% endblock %}


<!--内容-->
{% block content %}
    <div class="layui-card">
        <span class="layui-breadcrumb">
              <a href="{% url "index" %}">首页</a>
              <a href="#">kubernetes</a>
              <a><cite>persistent volumes节点</cite></a>
            </span>
        <div class="layui-card-body">
            <table id="demo" lay-filter="test"></table>
        </div>
    </div>
{% endblock %}



<!--js代码-->
{% block js %}
    <script type="text/html" id="toolbarDemo">
        <!--增加一个输入框-->
        <input type="text" name="name" class="layui-input" style="width: 150px;height: 30px;float: left">
        <button class="layui-btn layui-btn-sm" style="float: left" id="searchBtn">搜索</button>
        <a href="{% url "k8s:pv_create" %}" class="layui-btn layui-btn-sm" style="float: left">创建</a>
    </script>


    <script type="text/html" id="barDemo">
        <a class="layui-btn layui-btn-xs layui-btn-primary" lay-event="edit">YAML</a>
        <a class="layui-btn layui-btn-danger layui-btn-xs" lay-event="del">删除</a>
    </script>


    <script>
      // 获取当前命名空间
        var storage = window.sessionStorage;
        var namespace = storage.getItem("namespace");
        console.log(namespace)

        layui.use('table', function () {
            var table = layui.table;
            var layer = layui.layer;
            var $ = layui.jquery;

            table.render({
                elem: '#demo'
                , url: '{% url "k8s:pv_api" %}'
                , toolbar: '#toolbarDemo' //开启头部工具栏，并为其绑定左侧模板
                , defaultToolbar: ['filter', 'exports', 'print', { //自定义头部工具栏右侧图标。如无需自定义，去除该参数即可
                    title: '提示'
                    , layEvent: 'LAYTABLE_TIPS'
                    , icon: 'layui-icon-tips'
                }]
                , title: '数据表'
                , skin: 'line'         // 取消表格竖线
                , cols: [[
                    //{field: 'id', title: '序号', width: 80, fixed: 'left', type: 'numbers'},   // 序号排序，使用type：'numbers'
                    {field: 'name', title: '名称', width: 120, unresize: true, sort: true}
                    , {field: 'capacity', title: '容量', width: 80}
                    , {field: 'access_modes', title: '访问模式', width: 160}
                    , {field: 'reclaim_policy', title: '回收策略', width: 120}
                    , {field: 'status', title: '状态', width: 120}
                    , {field: 'pvc', title: 'PVC名称'}
                    , {field: 'storage_class', title: '存储类', templet: labelsFormat}
                    , {field: 'create_time', title: '创建时间'}
                    , {fixed: 'right', title: '操作', toolbar: '#barDemo', width: 160}
                ]]
                , page: true      // 设置分页
                , id: "pv"      // 设置表格重载， 这里使用必须是id："值"
            });


            function labelsFormat(d) {
                result = ""
                if (d.storage_class == null) {
                    return "None"
                } else {
                    for (let key in d.storage_class) {
                        result += key + "：" + d.storage_class[key] + "<br>"
                    }
                    return result
                }
            }


            //监听行工具事件
            table.on('tool(test)', function (obj) {
                var data = obj.data;
                //console.log(obj)
                if (obj.event === 'del') {
                    console.log(data)
                    layer.confirm('是否确定删除' + data["name"] + "这个命令空间吗", function (index) {
                        csrf_token = $('[name=csrfmiddlewaretoken]').val();

                        $.ajax({
                            type: "DELETE",
                            url: "{% url "k8s:pv_api" %}",
                            data: data,
                            headers: {"X-CSRFToken": csrf_token},
                            success: function (res) {
                                if (res.code == 0) {
                                    layer.msg(res.msg, {icon: 6});
                                    obj.del()  // 页面删除
                                } else {
                                    layer.msg(res.msg, {icon: 5})
                                }
                            },
                            error: function () {

                            },
                        });
                    });
                } else if (obj.event === 'edit') {
                    layer.open({
                        title: 'YAML',
                        type: 2,
                        area: ['50%', '60%'],
                        content: "{% url 'ace_editor' %}?resource=PersistentVolumes&" + 'namespace=' + data['namespace'] + '&name=' + data['name'],
                    })
                }
            });

            // 搜索功能
            $(document).on('click', '#searchBtn', function () {
                // 获取搜索的值
                var input_val = $('input[name=name]').val();

                // 判断用户是点击搜索按钮是否有值，没有就刷新当前页面，获取所有，否则就返回后端接口，刷新
                if (input_val == "" || input_val == null || input_val == undefined) { // "",null,undefined
                    console.log("为空")
                    window.parent.location.reload()
                } else {
                    table.reload('pv', {
                        where: { //设定异步数据接口的额外参数，任意设
                            // 要传回的key
                            searchkey: input_val
                        }
                        , page: {
                            curr: 1 //重新从第 1 页开始
                        }
                    }); //只重载数据
                }

            });


        });

    </script>


{% endblock %}

devops/templates/k8s/nodes.html
{% extends "base.html" %}

<!--头部-->
{% block title %} node节点 {% endblock %}
<!-停留的样式-->
<!--layui-nav-itemed 为开关-->
{% block nav-item-1 %} layui-nav-itemed {% endblock %}

<!--layui-this 停留的背景颜色-->
{% block nav-this-1-1 %} layui-this {% endblock %}


<!--内容-->
{% block content %}


    <div class="layui-card">
        <span class="layui-breadcrumb">
          <a href="{% url "index" %}">首页</a>
          <a href="#">kubernetes</a>
          <a><cite>node节点</cite></a>
        </span>
        <div class="layui-card-body">
            <table id="demo" lay-filter="test"></table>
        </div>
    </div>
{% endblock %}



<!--js代码-->
{% block js %}
    <script type="text/html" id="toolbarDemo">
        <!--增加一个输入框-->
        <input type="text" name="name" class="layui-input" style="width: 150px;height: 30px;float: left">
        <button class="layui-btn layui-btn-sm" style="float: left" id="searchBtn">搜索</button>

    </script>


    <script type="text/html" id="barDemo">
        <a class="layui-btn layui-btn-xs layui-btn-primary" lay-event="edit">YAML</a>
        <a class="layui-btn layui-btn-normal layui-btn-xs" lay-event="details">详情</a>
        <a class="layui-btn layui-btn-danger layui-btn-xs" lay-event="del">删除</a>

    </script>


    <script>
        layui.use('table', function () {
            var table = layui.table;
            var layer = layui.layer;
            var $ = layui.jquery;

            table.render({
                elem: '#demo'
                , url: '{% url "k8s:node_api" %}'
                , toolbar: '#toolbarDemo' //开启头部工具栏，并为其绑定左侧模板
                , defaultToolbar: ['filter', 'exports', 'print', { //自定义头部工具栏右侧图标。如无需自定义，去除该参数即可
                    title: '提示'
                    , layEvent: 'LAYTABLE_TIPS'
                    , icon: 'layui-icon-tips'
                }]
                , title: '数据表'
                , skin: 'line'         // 取消表格竖线
                , cols: [[
                    {field: 'name', title: '名称', sort: true}
                    , {field: 'labels', title: '标签', templet: labelsFormat}
                    , {field: 'status', title: '准备就绪'}
                    , {field: 'scheduler', title: '可调度'}
                    , {field: 'cpu', title: 'CPU'}
                    , {field: 'memory', title: '内存'}
                    , {field: 'kebelet_version', title: 'kubelet版本'}
                    , {field: 'cri_version', title: 'CRI版本'}
                    , {field: 'create_time', title: '创建时间'}
                    , {fixed: 'right', title: '操作', toolbar: '#barDemo', width: 180}
                ]]
                , page: true      // 设置分页
                , id: "ntb"      // 设置表格重载， 这里使用必须是id："值"
            });

            function labelsFormat(d) {
                result = ""
                if (d.labels == null) {
                    return "None"
                } else {
                    for (let key in d.labels) {
                        result += key + "：" + d.labels[key] + "<br>"
                    }
                    return result
                }
            }

            //监听行工具事件
            table.on('tool(test)', function (obj) {
                var data = obj.data;
                //console.log(obj)
                if (obj.event === 'del') {
                    console.log(data)
                    layer.confirm('是否确定删除' + data["name"] + "这个命令空间吗", function (index) {
                        csrf_token = $('[name=csrfmiddlewaretoken]').val();

                        $.ajax({
                            type: "DELETE",
                            url: "{% url "k8s:node_api" %}",
                            data: data,
                            headers: {"X-CSRFToken": csrf_token},
                            success: function (res) {
                                if (res.code == 0) {
                                    layer.msg(res.msg, {icon: 6});
                                    obj.del()  // 页面删除
                                } else {
                                    layer.msg(res.msg, {icon: 5})
                                }
                            },
                            error: function () {

                            },
                        });
                    });
                } else if (obj.event === 'edit') {
                    layer.open({
                        title: 'YAML',
                        type: 2,
                        area: ['60%', '60%'],
                        content: "{% url 'ace_editor' %}?resource=nodes&" + 'namespace=' + data['namespace'] + '&name=' + data['name'],
                    });
                } else  if (obj.event === 'details') {
                    // 使用前端的Windows跳转
                    window.location.href = "{% url 'k8s:node_details' %}?node_name=" + data["name"]
                };
            });

            // 搜索功能
            $(document).on('click', '#searchBtn', function () {
                // 获取搜索的值
                var input_val = $('input[name=name]').val();

                // 判断用户是点击搜索按钮是否有值，没有就刷新当前页面，获取所有，否则就返回后端接口，刷新
                if (input_val == "" || input_val == null || input_val == undefined) { // "",null,undefined
                    console.log("为空")
                    window.parent.location.reload()
                } else {
                    table.reload('ntb', {
                        where: { //设定异步数据接口的额外参数，任意设
                            // 要传回的key
                            searchkey: input_val
                        }
                        , page: {
                            curr: 1 //重新从第 1 页开始
                        }
                    }); //只重载数据
                }

            });


        });

    </script>


{% endblock %}

devops/templates/k8s/pv_create.html
{% extends "base.html" %}

<!--头部-->
{% block title %} pv节点 {% endblock %}
<!-停留的样式-->
<!--layui-nav-itemed 为开关-->
{% block nav-item-1 %} layui-nav-itemed {% endblock %}

<!--layui-this 停留的背景颜色-->
{% block nav-this-1-3 %} layui-this {% endblock %}


<!--内容-->
{% block content %}
    <span class="layui-breadcrumb">
      <a href="#">首页</a>
      <a href="#">Kubernetes</a>
      <a href="#">PersistentVolumes</a>
      <a><cite>创建</cite></a>
    </span>
    <hr>

        <div class="layui-card">
        <div class="layui-card-body">

        <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
          <legend>创建PersistentVolume</legend>
        </fieldset>
        <form class="layui-form " onclick="return false">
          <div class="layui-form-item">

            <label class="layui-form-label">名称：</label>
            <div class="layui-input-block">
              <input type="text" name="name" lay-verify="required" lay-reqtext="名称是必填项，不能为空！" placeholder="" autocomplete="off" class="layui-input">
            </div>

              <div class="layui-form-item" pane="">
                <label class="layui-form-label">存储容量：</label>
                <div class="layui-input-block">
                  <input type="radio" name="capacity" value="1Gi" title="1Gi" checked="">
                  <input type="radio" name="capacity" value="5Gi" title="5Gi">
                  <input type="radio" name="capacity" value="10Gi" title="10Gi">
                  <input type="radio" name="capacity" value="20Gi" title="20Gi" >
                  <input type="radio" name="capacity"  title="自定义" disabled="">
                </div>
              </div>

              <div class="layui-form-item" pane="">
                <label class="layui-form-label">访问模式：</label>
                <div class="layui-input-block">
                  <input type="radio" name="access_mode" value="ReadWriteMany" title="多节点读写" checked="">
                  <input type="radio" name="access_mode" value="ReadOnlyMany" title="多节点只读">
                  <input type="radio" name="access_mode" value="ReadWriteOnce" title="单节点读写">
                </div>
              </div>

            <div class="layui-inline">
              <label class="layui-form-label">存储类型：</label>
              <div class="layui-input-inline">
                <select name="storage_class">
                  <option value=""></option>
                  <optgroup label="单点存储(适合非核心业务)">
                    <option value="nfs">NFS</option>
                  </optgroup>
                  <optgroup label="分布式存储(暂不支持)">
                    <option value="cephfs">CephFS</option>
                    <option value="cephrbd">CephRBD</option>
                  </optgroup>
                </select>
              </div>
            </div>

              <div style="padding-left: 30px">
                 <label class="layui-form-label">服务器IP：</label>
                 <div class="layui-input-block">
                   <select name="server_ip"  lay-verify="required" lay-search="" lay-filter="select_ns2">
                      <option value="">直接选择或搜索选择</option>
                      <option value="192.168.31.62">172.17.0.3</option>
                      <option value="192.168.31.63">172.17.0.2</option>
                    </select>
                 </div>
                 <label class="layui-form-label">挂载路径：</label>
                 <div class="layui-input-block">
                  <input type="text" name="mount_path" lay-verify="required" lay-reqtext="名称是必填项，不能为空！" placeholder="示例：pv0001" autocomplete="off" class="layui-input">
                 </div>

              </div>

              <br>
              <div class="layui-form-item">
                <div class="layui-input-block">
                  <button type="submit" class="layui-btn" lay-submit="" lay-filter="btn">立即提交</button>
                  <button type="reset" class="layui-btn layui-btn-primary">重置</button>
                </div>
              </div>

          </div>
        </form>

        </div>
    </div>


{% endblock %}

{% block js %}
<script>
layui.use(['table','form','layer'], function(){
  var table = layui.table;
  var layer = layui.layer;
  var form = layui.form;
  var $ = layui.jquery;

  // 监听提交
  form.on('submit(btn)', function (data) {
      data = data.field;
      csrf_token = $('[name="csrfmiddlewaretoken"]').val();
      data['csrfmiddlewaretoken'] = csrf_token;
        $.ajax({
            url: '{% url 'k8s:pv_api' %}',
            type: "POST",
            data: data,
            headers: {"X-CSRFToken": csrf_token},
            success: function (res) {
                if (res.code == 0) {
                    layer.msg(res.msg, {icon: 6});
                    window.location.href = "{% url 'k8s:PersistentVolumes' %}"   // 刷新页面，并跳转
                } else {
                    layer.msg(res.msg, {icon: 5})
                }
            },
            error: function () {
                layer.msg("服务器接口异常",{icon: 5})
            }
        })
  })

});
</script>

{% endblock %}