devops/devops/urls.py
from django.contrib import admin
from django.urls import path,re_path,include
from dashboard import views


urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('^$',views.index, name="index"),          # 登陆后台首页接口
    re_path('^login/$',views.login, name="login"),    # login登陆接口
    re_path('^logout/$',views.logout, name="logout"),    # logout退出登录接口
    re_path('^namespace_api/$',views.namespace_api, name="namespace_api"),    # 匿名空间api接口
    re_path('^node_resource/$', views.node_resource, name="node_resource"),   # index页面调用的计算资源接口
    re_path('^export_resource_api/$',views.export_resource_api, name="export_resource_api"),    # 编写yaml获取数据接口
    re_path('^ace_editor/$',views.ace_editor, name="ace_editor"),    # 编写yaml获取数据接口
    path('k8s/', include(('k8s.urls', 'k8s'), namespace='k8s')),            # k8s模块
    path('workload/', include(('workload.urls', 'workload'), namespace='workload')),     # workload模块
    path('loadbalancer/', include(('loadbalancer.urls', 'loadbalancer'), namespace='loadbalancer')),    # loadbalancer模块
    path('storage/', include(('storage.urls', 'storage'), namespace='storage')),    # storage模块，主要用于存储一些文件配置与存储

]

devops/k8s/urls.py
from django.urls import path,re_path
from k8s import views


urlpatterns = [
    re_path('^nodes/$',views.nodes, name="nodes"),                # node调用的前端页面调用接口
    re_path('^namespaces/$',views.namespaces, name="namespaces"),        # namespaces调用的前端页面展示接口
    re_path('^PersistentVolumes/$',views.PersistentVolumes, name="PersistentVolumes"),        # pv前端展示接口
    re_path('^node_api/$',views.node_api, name="node_api"),                       # 调用的node_api接口
    re_path('^node_details/$',views.node_details, name="node_details"),           # 调用node详情页前端页面展示接口
    re_path('^node_details_pod_list/$',views.node_details_pod_list, name="node_details_pod_list"),    # 调用node详情页，后端api接口
    re_path('^pv_api/$',views.pv_api, name="pv_api"),            # pv调用的后端的api接口
    re_path('^pv_create/$',views.pv_create, name="pv_create"),     # 创建pv调用的前端接口

]

devops/workload/urls.py
from django.urls import path,re_path
from workload import views


urlpatterns = [
    re_path('^deployments/$',views.deployments, name="deployments"),             # deployments展示页面接口
    re_path('^deployments_create/$',views.deployments_create, name="deployments_create"),   # deployments创建页面接口
    re_path('^daemonsets/$',views.daemonsets, name="daemonsets"),                       # daemonsets 展示页面接口
    re_path('^daemonsets_create/$',views.daemonsets_create, name="daemonsets_create"),
    re_path('^statefulsets/$',views.statefulsets, name="statefulsets"),
    re_path('^statefulsets_create/$',views.statefulsets_create, name="statefulsets_create"),
    re_path('^pods/$',views.pods, name="pods"),
    re_path('^deployments_api/$',views.deployments_api, name="deployments_api"),
    re_path('^deployments_details/$',views.deployments_details, name="deployments_details"),
    re_path('^daemonsets_api/$',views.daemonsets_api, name="daemonsets_api"),
    re_path('^statefulsets_api/$', views.statefulsets_api, name="statefulsets_api"),
    re_path('^pods_api/$', views.pods_api, name="pods_api"),
    re_path('^replicaset_api/$', views.replicaset_api, name="replicaset_api"),    # 用于deployments详情页查询数据
    re_path('^pods_log/$', views.pods_log, name="pods_log"),    # 用于pods的日志查看
    re_path('^terminal/$', views.terminal, name="terminal"),    # 用于pod的容器终端
]

devops/workload/models.py
from django.db import models

# Create your models here.

devops/workload/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse, QueryDict
from kubernetes import client, config
import os, hashlib, random
from devops import k8s_tools  # 导入k8s登陆封装


# deployments 页面展示
@k8s_tools.self_login_required
def deployments(request):
    return render(request, "workload/deployments.html")


# deployments_create 创建页面
@k8s_tools.self_login_required
def deployments_create(request):
    return render(request, "workload/deployments_create.html")


# daemonset 页面展示
@k8s_tools.self_login_required
def daemonsets(request):
    return render(request, "workload/daemonsets.html")


# daemonsets_create 创建页面
@k8s_tools.self_login_required
def daemonsets_create(request):
    return render(request, "workload/daemonsets_create.html")


# deployments_details 创建页面
@k8s_tools.self_login_required
def deployments_details(request):
    auth_type = request.session.get("auth_type")
    token = request.session.get("token")
    k8s_tools.load_auth_config(auth_type, token)
    core_api = client.CoreV1Api()
    apps_api = client.AppsV1Api()
    networking_api = client.NetworkingV1beta1Api()

    dp_name = request.GET.get("name")
    namespace = request.GET.get("namespace")

    dp_info = []
    for dp in apps_api.list_namespaced_deployment(namespace=namespace).items:
        if dp_name == dp.metadata.name:
            name = dp.metadata.name
            namespace = dp.metadata.namespace
            replicas = dp.spec.replicas
            available_replicas = (
                0 if dp.status.available_replicas is None else dp.status.available_replicas)  # ready_replicas
            labels = dp.metadata.labels
            selector = dp.spec.selector.match_labels

            # 通过deployment反查对应service
            service = []
            svc_name = None
            for svc in core_api.list_namespaced_service(namespace=namespace).items:
                if svc.spec.selector == selector:
                    svc_name = svc.metadata.name  # 通过该名称筛选ingress
                    type = svc.spec.type
                    cluster_ip = svc.spec.cluster_ip
                    ports = svc.spec.ports

                    data = {"type": type, "cluster_ip": cluster_ip, "ports": ports}
                    service.append(data)

            # service没有创建，ingress也就没有  ingress->service->deployment->pod
            ingress = {"rules": None, "tls": None}
            for ing in networking_api.list_namespaced_ingress(namespace=namespace).items:
                for r in ing.spec.rules:
                    for b in r.http.paths:
                        if b.backend.service_name == svc_name:
                            ingress["rules"] = ing.spec.rules
                            ingress["tls"] = ing.spec.tls

            containers = []
            for c in dp.spec.template.spec.containers:
                c_name = c.name
                image = c.image
                liveness_probe = c.liveness_probe
                readiness_probe = c.readiness_probe
                resources = c.resources  # 在前端处理
                env = c.env
                ports = c.ports
                volume_mounts = c.volume_mounts
                args = c.args
                command = c.command

                container = {"name": c_name, "image": image, "liveness_probe": liveness_probe,
                             "readiness_probe": readiness_probe,
                             "resources": resources, "env": env, "ports": ports,
                             "volume_mounts": volume_mounts, "args": args, "command": command}
                containers.append(container)

            tolerations = dp.spec.template.spec.tolerations
            rolling_update = dp.spec.strategy.rolling_update
            volumes = []
            if dp.spec.template.spec.volumes is not None:
                for v in dp.spec.template.spec.volumes:
                    volume = {}
                    if v.config_map is not None:
                        volume["config_map"] = v.config_map
                    elif v.secret is not None:
                        volume["secret"] = v.secret
                    elif v.empty_dir is not None:
                        volume["empty_dir"] = v.empty_dir
                    elif v.host_path is not None:
                        volume["host_path"] = v.host_path
                    elif v.config_map is not None:
                        volume["downward_api"] = v.downward_api
                    elif v.config_map is not None:
                        volume["glusterfs"] = v.glusterfs
                    elif v.cephfs is not None:
                        volume["cephfs"] = v.cephfs
                    elif v.rbd is not None:
                        volume["rbd"] = v.rbd
                    elif v.persistent_volume_claim is not None:
                        volume["persistent_volume_claim"] = v.persistent_volume_claim
                    else:
                        volume["unknown"] = "unknown"
                    volumes.append(volume)

            rs_number = dp.spec.revision_history_limit
            create_time = k8s_tools.dt_format(dp.metadata.creation_timestamp)

            dp_info = {"name": name, "namespace": namespace, "replicas": replicas,
                       "available_replicas": available_replicas, "labels": labels,
                       "selector": selector, "containers": containers, "rs_number": rs_number,
                       "rolling_update": rolling_update, "create_time": create_time, "volumes": volumes,
                       "tolerations": tolerations, "service": service, "ingress": ingress}
    return render(request, 'workload/deployments_details.html',
                  {'dp_name': dp_name, 'namespace': namespace, 'dp_info': dp_info})


@k8s_tools.self_login_required
def replicaset_api(request):
    auth_type = request.session.get("auth_type")
    token = request.session.get("token")
    k8s_tools.load_auth_config(auth_type, token)
    apps_api = client.AppsV1Api()
    apps_beta_api = client.ExtensionsV1beta1Api()

    if request.method == "GET":
        dp_name = request.GET.get("name", None)
        namespace = request.GET.get("namespace", None)
        data = []
        for rs in apps_api.list_namespaced_replica_set(namespace=namespace).items:
            current_dp_name = rs.metadata.owner_references[0].name
            rs_name = rs.metadata.name
            if dp_name == current_dp_name:
                namespace = rs.metadata.namespace
                replicas = rs.status.replicas
                available_replicas = rs.status.available_replicas
                ready_replicas = rs.status.ready_replicas
                revision = rs.metadata.annotations["deployment.kubernetes.io/revision"]
                create_time = k8s_tools.dt_format(rs.metadata.creation_timestamp)

                containers = {}
                for c in rs.spec.template.spec.containers:
                    containers[c.name] = c.image

                rs = {"name": rs_name, "namespace": namespace, "replicas": replicas,
                      "available_replicas": available_replicas, "ready_replicas": ready_replicas,
                      "revision": revision, 'containers': containers, "create_time": create_time}
                data.append(rs)
        count = len(data)  # 可选，rs默认保存10条，所以不用分页
        res = {"code": 0, "msg": "", "count": count, 'data': data}
        return JsonResponse(res)
    elif request.method == "POST":
        dp_name = request.POST.get("dp_name", None)  # deployment名称
        namespace = request.POST.get("namespace", None)
        reversion = request.POST.get("reversion", None)
        body = {"name": dp_name, "rollback_to": {"revision": reversion}}
        print(dp_name)
        try:
            apps_beta_api.create_namespaced_deployment_rollback(name=dp_name, namespace=namespace, body=body)
            code = 0
            msg = "回滚成功！"
        except Exception as e:
            print(e)
            status = getattr(e, "status")
            if status == 403:
                msg = "你没有回滚权限！"
            else:
                msg = "回滚失败！"
            code = 1
        res = {"code": code, "msg": msg}
        return JsonResponse(res)


# statefulset 页面展示
@k8s_tools.self_login_required
def statefulsets(request):
    return render(request, "workload/statefulsets.html")


# statefulsets_create 创建页面
@k8s_tools.self_login_required
def statefulsets_create(request):
    return render(request, "workload/statefulsets_create.html")


# pods 页面展示
@k8s_tools.self_login_required
def pods(request):
    return render(request, "workload/pods.html")


# deployments_api接口
@k8s_tools.self_login_required
def deployments_api(request):
    code = 0
    msg = ""
    auth_type = request.session.get("auth_type")
    token = request.session.get("token")
    k8s_tools.load_auth_config(auth_type, token)
    apps_api = client.AppsV1Api()
    if request.method == "GET":
        search_key = request.GET.get("search_key")
        namespace = request.GET.get("namespace")
        data = []
        try:
            for dp in apps_api.list_namespaced_deployment(namespace=namespace).items:
                name = dp.metadata.name
                namespace = dp.metadata.namespace
                replicas = dp.spec.replicas
                available_replicas = (0 if dp.status.available_replicas is None else dp.status.available_replicas)
                labels = dp.metadata.labels
                selector = dp.spec.selector.match_labels
                if len(dp.spec.template.spec.containers) > 1:
                    images = ""
                    n = 1
                    for c in dp.spec.template.spec.containers:
                        status = ("运行中" if dp.status.conditions[0].status == "True" else "异常")
                        image = c.image
                        images += "[%s]: %s / %s" % (n, image, status)
                        images += "<br>"
                        n += 1
                else:
                    status = (

devops/templates/workload/deployments.html
{% extends "base.html" %}

<!--头部-->
{% block title %} dp节点 {% endblock %}
<!-停留的样式-->

<!--layui-nav-itemed 为开关-->
{% block nav-item-2 %} layui-nav-itemed {% endblock %}

<!--layui-this 停留的背景颜色-->
{% block nav-this-2-1 %} layui-this  {% endblock %}


<!--内容-->
{% block content %}
    <div class="layui-card">
        <div class="layui-card-body">
            <table id="demo" lay-filter="test"></table>
        </div>
    </div>
{% endblock %}



<!--js代码-->
{% block js %}
    <script type="text/html" id="toolbarDemo">
        <!--增加一个输入框-->
        <input type="text" name="name" class="layui-input" style="width: 150px;height: 30px;float: left">
        <button class="layui-btn layui-btn-sm" style="float: left" id="searchBtn">搜索</button>
        <a href="{% url 'workload:deployments_create' %}" class="layui-btn layui-btn-sm" style="float: left">创建</a>
    </script>


    <script type="text/html" id="barDemo">
        <a class="layui-btn layui-btn-xs layui-btn-primary" lay-event="edit">YAML</a>
        <a class="layui-btn layui-btn-normal layui-btn-xs" lay-event="details">详情</a>
        <a class="layui-btn layui-bg-green layui-btn-xs" lay-event="scale">扩容/缩容</a>
        <a class="layui-btn layui-btn-danger layui-btn-xs" lay-event="del">删除</a>
    </script>

    <script>

        // 获取当前命名空间
        var storage = window.sessionStorage;
        var namespace = storage.getItem("namespace");

        layui.use('table', function () {
            var table = layui.table;
            var layer = layui.layer;
            var $ = layui.jquery;

            table.render({
                elem: '#demo'
                , url: '{% url "workload:deployments_api" %}?namespace=' + namespace      // 调用接口数据，并返回全局命名空间值
                , toolbar: '#toolbarDemo' //开启头部工具栏，并为其绑定左侧模板
                , defaultToolbar: ['filter', 'exports', 'print', { //自定义头部工具栏右侧图标。如无需自定义，去除该参数即可
                    title: '提示'
                    , layEvent: 'LAYTABLE_TIPS'
                    , icon: 'layui-icon-tips'
                }]
                , title: '数据表'
                , skin: 'line'         // 取消表格竖线
                , cols: [[
                    //{field: 'id', title: '序号', width: 80, fixed: 'left', type: 'numbers'},   // 序号排序，使用type：'numbers'
                    {field: 'name', title: '名称', width: 180, unresize: true, sort: true}
                    , {field: 'namespace', title: '命名空间', width: 120}
                    , {field: 'replicas', title: '预期副本数', width: 100}
                    , {field: 'available_replicas', title: '可用副本数', width: 100}
                    , {field: 'labels', title: '标签', templet: labelsFormat}
                    , {field: 'selector', title: 'Pod标签选择器', templet: selecotrFormat}
                    , {field: 'containers', title: '容器', templet: containersFormat}
                    , {field: 'create_time', title: '创建时间'}
                    , {fixed: 'right', title: '操作', toolbar: '#barDemo', width: 250}
                ]]
                , page: true      // 设置分页
                , id: "dp"      // 设置表格重载， 这里使用必须是id："值"
            });

            // 标签格式化，是一个对象
            function labelsFormat(d) {
                result = "";
                if (d.labels == null) {
                    return "None"
                } else {
                    for (let key in d.labels) {
                        result += '<span style="border: 1px solid #d6e5ec;border-radius: 8px">' +
                            key + ':' + d.labels[key] +
                            '</span><br>'
                    }
                    return result
                }
            }

            function selecotrFormat(d) {
                result = "";
                for (let key in d.selector) {
                    result += '<span style="border: 1px solid #d6e5ec;border-radius: 8px">' +
                        key + ':' + d.selector[key] +
                        '</span><br>'
                }
                return result
            }

            function containersFormat(d) {
                result = "";

                // 使用if判断值是否返回为空，为空重新填写数据，否则就返回正常值
                if (d.containers == null) {
                    return "None"
                } else {
                    for (let key in d.containers) {
                        result += key + '=' + d.containers[key] + '<br>'
                    }
                    return result
                }

            }

            //监听行工具事件
            table.on('tool(test)', function (obj) {
                var data = obj.data;
                //console.log(obj)
                if (obj.event === 'del') {
                    console.log(data)
                    layer.confirm('是否确定删除' + data["name"] + "这个命令空间吗", function (index) {
                        csrf_token = $('[name=csrfmiddlewaretoken]').val();

                        $.ajax({
                            type: "DELETE",
                            url: "{% url "workload:deployments_api" %}",
                            data: data,
                            headers: {"X-CSRFToken": csrf_token},
                            success: function (res) {
                                if (res.code == 0) {
                                    layer.msg(res.msg, {icon: 6});
                                    obj.del()  // 页面删除
                                } else {
                                    layer.msg(res.msg, {icon: 5})
                                }
                            },
                            error: function () {

                            },
                        });
                    });
                    // 启动编辑查看功能，yaml配置文件
                } else if (obj.event === 'edit') {
                    layer.open({
                        title: 'YAML',
                        type: 2,
                        area: ['60%', '60%'],
                        content: "{% url 'ace_editor' %}?resource=deployments&" + 'namespace=' + data['namespace'] + '&name=' + data['name'],
                    });
                } else if (obj.event === 'details') {
                    window.location.href = "{% url "workload:deployments_details" %}?namespace=" + data["namespace"] + "&name=" + data["name"]

                } else if (obj.event === 'scale') {
                    // 编写扩容/缩容接口对接，使用PUT功能提交
                    layer.prompt({
                        formType: 0
                        , title: "扩容/缩容"
                        , value: data.replicas   // 默认值，从当前字段获取
                    }, function (value, index) {
                        csrf_token = $('[name="csrfmiddlewaretoken"]').val();
                        data['replicas'] = value;  // value是表单输入的值，重置值
                        $.ajax({
                            url: '{% url "workload:deployments_api" %}',
                            type: "PUT",
                            data: data,
                            headers: {"X-CSRFToken": csrf_token},
                            success: function (res) {
                                if (res.code == '0') {
                                    layer.msg(res.msg, {icon: 6}); //2秒关闭（如果不配置，默认是3秒）
                                    // 更新当前页面字段值
                                    obj.update({
                                        replicas: value
                                    })
                                } else {
                                    layer.msg(res.msg, {icon: 5})
                                }
                            }
                        });
                        layer.close(index);  // 关闭弹窗
                    });
                }
            });

            // 搜索功能
            $(document).on('click', '#searchBtn', function () {
                // 获取搜索的值
                var input_val = $('input[name=name]').val();

                // 判断用户是点击搜索按钮是否有值，没有就刷新当前页面，获取所有，否则就返回后端接口，刷新
                if (input_val == "" || input_val == null || input_val == undefined) { // "",null,undefined
                    console.log("为空")
                    window.parent.location.reload()
                } else {
                    table.reload('dp', {
                        where: { //设定异步数据接口的额外参数，任意设
                            // 要传回的key
                            searchkey: input_val
                        }
                        , page: {
                            curr: 1 //重新从第 1 页开始
                        }
                    }); //只重载数据
                }

            });


        });

    </script>


{% endblock %}

devops/templates/workload/pods.html
{% extends "base.html" %}

<!--头部-->
{% block title %} pods节点 {% endblock %}
<!-停留的样式-->
<!--layui-nav-itemed 为开关-->
{% block nav-item-2 %} layui-nav-itemed {% endblock %}

<!--layui-this 停留的背景颜色-->
{% block nav-this-2-4 %}layui-this {% endblock %}


<!--内容-->
{% block content %}
    <!--设置日志显示背景颜色-->
    <div id="modal" style="display: none">
        <form class="layui-form " action="">
            <div id="log-text" class="layui-form-item"
                 style="background-color: black;color: white;padding: 10px;font-size: 16px">
            </div>
        </form>
    </div>
    <div class="layui-card">
        <div class="layui-card-body">
            <table id="demo" lay-filter="test"></table>
        </div>
    </div>
{% endblock %}



<!--js代码-->
{% block js %}
    <script type="text/html" id="toolbarDemo">
        <!--增加一个输入框-->
        <input type="text" name="name" class="layui-input" style="width: 150px;height: 30px;float: left">
        <button class="layui-btn layui-btn-sm" style="float: left" id="searchBtn">搜索</button>
    </script>


    <script type="text/html" id="barDemo">
        <a class="layui-btn layui-btn-xs layui-btn-primary" lay-event="edit">YAML</a>
        <a class="layui-btn layui-btn-normal layui-btn-xs" lay-event="terminal">终端</a>
        <a class="layui-btn layui-btn-xs layui-bg-green" lay-event="log">查看日志</a>
        <a class="layui-btn layui-btn-danger layui-btn-xs" lay-event="del">删除</a>
    </script>

    <script>

        // 获取当前命名空间
        var storage = window.sessionStorage;
        var namespace = storage.getItem("namespace");


        layui.use('table', function () {
            var table = layui.table;
            var layer = layui.layer;
            var $ = layui.jquery;

            table.render({
                elem: '#demo'
                , url: '{% url "workload:pods_api" %}?namespace=' + namespace      // 调用接口数据，并返回全局命名空间值
                , toolbar: '#toolbarDemo' //开启头部工具栏，并为其绑定左侧模板
                , defaultToolbar: ['filter', 'exports', 'print', { //自定义头部工具栏右侧图标。如无需自定义，去除该参数即可
                    title: '提示'
                    , layEvent: 'LAYTABLE_TIPS'
                    , icon: 'layui-icon-tips'
                }]
                , title: '数据表'
                , skin: 'line'         // 取消表格竖线
                , cols: [[
                    //{field: 'id', title: '序号', width: 80, fixed: 'left', type: 'numbers'},   // 序号排序，使用type：'numbers'
                    {field: 'name', title: '名称', sort: true}
                    , {field: 'namespace', title: '命名空间', sort: true, width: 120}
                    , {field: 'pod_ip', title: 'IP地址', width: 160}
                    , {field: 'labels', title: '标签', templet: labelsFormat}
                    , {field: 'containers', title: '容器组', templet: containersFormat}
                    , {field: 'status', title: '状态', sort: true, templet: statusFormat}
                    , {field: 'create_time', title: '创建时间'}
                    , {fixed: 'right', title: '操作', toolbar: '#barDemo', width: 250}
                ]]
                , page: true      // 设置分页
                , id: "po"      // 设置表格重载， 这里使用必须是id："值"
            });

            // 标签格式化，是一个对象
            function labelsFormat(d) {
                result = "";
                if (d.labels == null) {
                    return "None"
                } else {
                    for (let key in d.labels) {
                        result += '<span style="border: 1px solid #d6e5ec;border-radius: 8px">' +
                            key + ':' + d.labels[key] +
                            '</span><br>'
                    }
                    return result
                }
            }

            function containersFormat(d) {
                result = "";
                if (d.containers) {
                    for (let key in d.containers) {
                        data = d.containers[key];
                        result += key + ':' + data.c_name + '=' + data.c_image + '<br>' +
                            '重启次数:' + data.restart_count + '<br>' +
                            '状态:' + data.c_status + '<br>'
                    }
                    return result
                } else {
                    return "None"
                }
            }

            // 如果status为None，使用容器状态显示
            function statusFormat(d) {
                result = "";
                if (d.status == "None") {
                    for (let key in d.containers) {
                        result += d.containers[key].c_status + '<br>'
                    }
                    return result
                } else {
                    return d.status
                }
            }

            //监听行工具事件
            table.on('tool(test)', function (obj) {
                var data = obj.data;
                //console.log(obj)
                if (obj.event === 'del') {
                    console.log(data)
                    layer.confirm('是否确定删除' + data["name"] + "这个命令空间吗", function (index) {
                        csrf_token = $('[name=csrfmiddlewaretoken]').val();

                        $.ajax({
                            type: "DELETE",
                            url: "{% url "workload:pods_api" %}",
                            data: data,
                            headers: {"X-CSRFToken": csrf_token},
                            success: function (res) {
                                if (res.code == 0) {
                                    layer.msg(res.msg, {icon: 6});
                                    obj.del()  // 页面删除
                                } else {
                                    layer.msg(res.msg, {icon: 5})
                                }
                            },
                            error: function () {

                            },
                        });
                    });
                } else if (obj.event === 'edit') {
                    layer.open({
                        title: 'YAML',
                        type: 2,
                        area: ['60%', '60%'],
                        content: "{% url 'ace_editor' %}?resource=pods&" + 'namespace=' + data['namespace'] + '&name=' + data['name'],
                    });
                } else if (obj.event === 'log') {
                    // 逗号拼接容器名, 例如containers=c1,c2
                    cs = data['containers'];
                    containers = "";
                    for (let c in cs) {
                        if (c < cs.length - 1) {
                            containers += cs[c]['c_name'] + ","
                        } else {
                            containers += cs[c]['c_name']
                        }
                    }
                    layer.open({
                        title: "容器终端",
                        type: 2,
                        area: ['60%', '70%'],
                        content: '{% url "workload:pods_log" %}?namespace=' + data.namespace + '&pod_name=' + data.name + '&containers=' + containers
                    });
                } else if (obj.event === 'terminal') {
                    // 逗号拼接容器名, 例如containers=c1,c2
                    cs = data['containers'];
                    containers = "";
                    for (let c in cs) {
                        if (c < cs.length - 1) {
                            containers += cs[c]['c_name'] + ","
                        } else {
                            containers += cs[c]['c_name']
                        }
                    }
                    layer.open({
                        title: "容器终端",
                        type: 2,  // 加载层，从另一个网址引用
                        area: ['80%', '90%'],
                        content: '{% url "workload:terminal" %}?namespace=' + data["namespace"] + "&pod_name=" + data["name"] + "&containers=" + containers,
                    });
                }
            });

            // 搜索功能
            $(document).on('click', '#searchBtn', function () {
                // 获取搜索的值
                var input_val = $('input[name=name]').val();

                // 判断用户是点击搜索按钮是否有值，没有就刷新当前页面，获取所有，否则就返回后端接口，刷新
                if (input_val == "" || input_val == null || input_val == undefined) { // "",null,undefined
                    console.log("为空")
                    window.parent.location.reload()
                } else {
                    table.reload('po', {
                        where: { //设定异步数据接口的额外参数，任意设
                            // 要传回的key
                            searchkey: input_val
                        }
                        , page: {
                            curr: 1 //重新从第 1 页开始
                        }
                    }); //只重载数据
                }

            });


        });

    </script>


{% endblock %}